name: Test Workflow with Secrets

on:
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Secret in Environment
        run: |
          echo "FTP_USER is set to ${{ secrets.FTP_USER}}"
